name: Deploy to Main Branch

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        
      - name: Add .nojekyll
        run: touch dist/.nojekyll
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./dist
          force_orphan: true
          commit_message: 'Deploy: '