name: Deploy to gh-pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Clean workspace
        run: |
          git clean -fdx
          rm -rf node_modules/

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Verify build output
        run: ls -la dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./src
          force_orphan: true
          user_name: "GitHub Actions Bot"
          user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy: ${{ github.sha }}"