name: Deploy to gh-pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # 新增以下步骤 ▼▼▼
      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Verify build output
        run: |
          echo "=== 构建产物验证 ==="
          ls -la dist/
          [ -f dist/index.html ] || exit 1  # 强制验证index.html存在
          echo "==================="

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist  # ✅ 修改为正确路径
          force_orphan: true
          commit_message: "Deploy: ${{ github.sha }}"