name: Deploy to gh-pages

on:
  push:
    branches: [main]  # main 分支更新时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键权限配置
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build
        run: npm run build
        working-directory: ./client

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # 目标分支
          publish_dir: ./client       # 构建输出目录
          force_orphan: true        # 强制清空分支历史
          commit_message: "Deploy: ${{ github.sha }}"